project_name: jflint-go
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/masakichi/jflint-go/cmd.version=v{{ .Version }} -X github.com/masakichi/jflint-go/cmd.gitCommit={{ .ShortCommit }} -X github.com/masakichi/jflint-go/cmd.buildDate={{ .Date }}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
brews:
  - tap:
      owner: masakichi
      name: homebrew-tap
    folder: Formula
    license: "MIT"
    homepage: "https://github.com/masakichi/jflint-go"
    description: "jflint-go helps to lint a Declarative Jenkinsfile."
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-dev"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
